# Site Settings
title: DBA Technology
email: denis.willian1992@gmail.com
description: Come with me in a fantastic travel to Technology World!
baseurl: ""
url: "https://dedewillian.github.io"
google_analytics: "UA-119586029-1"

# User Settings
username: Denis Willian Oliveira
user_description: SQL Server DBA with passion for excellence and sharing!
github_username: dedewillian
facebook_username: denis.willian
twitter_username: ""
instagram_username: ""
linkedin_username: ""
medium_username: 
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jekyll-redirect-from
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Portfolio
    url: /portfolio/
  - title: About me
    url: /about-me/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
