# Site Settings
title: Victor Prado de Godoy | Back-End Developer
email: victorpradodegodoy09@gmail.com
description: Come with me in a fantastic travel to Technology World!
baseurl: ""
url: "https://vgodoy.gq/"
google_analytics: "UA-119586029-1"

# User Settings
username: Victor Prado de godoy
user_description: Java Developer with passion for excellence and sharing!
github_username: vgodoy09
facebook_username: victor.pradodegodoy
twitter_username: vpg_godoy
instagram_username: victao_godoy/?hl=pt-br
linkedin_username: victor-godoy-java-developer
medium_username: 
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jekyll-redirect-from
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Portfolio
    url: /portfolio/
  - title: About me
    url: /about-me/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
